# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "F:/DOCUMENTOS/FATECE/Box Sync/Privado/lab/NVetor"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "F:/DOCUMENTOS/FATECE/Box Sync/Privado/lab/NVetor"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "F:/DOCUMENTOS/FATECE/Box Sync/Privado/lab/NVetor/CMakeFiles" "F:/DOCUMENTOS/FATECE/Box Sync/Privado/lab/NVetor/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "F:/DOCUMENTOS/FATECE/Box Sync/Privado/lab/NVetor/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runtest

# Build rule for target.
runtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runtest
.PHONY : runtest

# fast build rule for target.
runtest/fast:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/build
.PHONY : runtest/fast

src/Vetor.obj: src/Vetor.cpp.obj

.PHONY : src/Vetor.obj

# target to build an object file
src/Vetor.cpp.obj:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor.cpp.obj
.PHONY : src/Vetor.cpp.obj

src/Vetor.i: src/Vetor.cpp.i

.PHONY : src/Vetor.i

# target to preprocess a source file
src/Vetor.cpp.i:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor.cpp.i
.PHONY : src/Vetor.cpp.i

src/Vetor.s: src/Vetor.cpp.s

.PHONY : src/Vetor.s

# target to generate assembly for a file
src/Vetor.cpp.s:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor.cpp.s
.PHONY : src/Vetor.cpp.s

src/Vetor3D.obj: src/Vetor3D.cpp.obj

.PHONY : src/Vetor3D.obj

# target to build an object file
src/Vetor3D.cpp.obj:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor3D.cpp.obj
.PHONY : src/Vetor3D.cpp.obj

src/Vetor3D.i: src/Vetor3D.cpp.i

.PHONY : src/Vetor3D.i

# target to preprocess a source file
src/Vetor3D.cpp.i:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor3D.cpp.i
.PHONY : src/Vetor3D.cpp.i

src/Vetor3D.s: src/Vetor3D.cpp.s

.PHONY : src/Vetor3D.s

# target to generate assembly for a file
src/Vetor3D.cpp.s:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/Vetor3D.cpp.s
.PHONY : src/Vetor3D.cpp.s

src/comum.obj: src/comum.cpp.obj

.PHONY : src/comum.obj

# target to build an object file
src/comum.cpp.obj:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/comum.cpp.obj
.PHONY : src/comum.cpp.obj

src/comum.i: src/comum.cpp.i

.PHONY : src/comum.i

# target to preprocess a source file
src/comum.cpp.i:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/comum.cpp.i
.PHONY : src/comum.cpp.i

src/comum.s: src/comum.cpp.s

.PHONY : src/comum.s

# target to generate assembly for a file
src/comum.cpp.s:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/src/comum.cpp.s
.PHONY : src/comum.cpp.s

tests.obj: tests.cpp.obj

.PHONY : tests.obj

# target to build an object file
tests.cpp.obj:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/tests.cpp.obj
.PHONY : tests.cpp.obj

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/runtest.dir/build.make CMakeFiles/runtest.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... runtest"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Vetor.obj"
	@echo "... src/Vetor.i"
	@echo "... src/Vetor.s"
	@echo "... src/Vetor3D.obj"
	@echo "... src/Vetor3D.i"
	@echo "... src/Vetor3D.s"
	@echo "... src/comum.obj"
	@echo "... src/comum.i"
	@echo "... src/comum.s"
	@echo "... tests.obj"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

